services:
  - type: web
    name: water-quality-backend
    env: python
    buildCommand: bash build.sh
    startCommand: gunicorn --config gunicorn_config.py app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: FLASK_ENV
        value: production
    plan: free
